### PR TITLE
Fixed issue of being unable to scroll into view of button and unable to find "raffle-enter" id.

### PR DESCRIPTION
**Pull request by Powtaitoe**
I removed the scroll before entering the raffle and the script will straight up click the button instead. Also fixed the issue of the script being unable to find the button id by changing the div focus. Might not work 100%

### CODE REVIEW

**Comment by Powtaitoe** [comment]
Nevermind, it gets you banned xD

**Comment by iraizo** [comment]
you will need to add some randomization or look at their clientside "anticheat"

**Comment by Powtaitoe** [comment]
I kept your randomization of entering scripts. I will look into their client-side

**Comment by Powtaitoe** [comment]
BTW, your script still doesn't work. xD

**Comment by Powtaitoe** [comment]
> you will need to add some randomization or look at their clientside "anticheat"

btw, how do I look at their cilentside "anticheat"?

**Pull request closed without merging**
